apiVersion: v1
kind: Service
metadata:
  name: globeco-security-service
  namespace: globeco
spec:
  selector:
    app: globeco-security-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP 