apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: security-service-mongodb-pvc
  namespace: globeco
  labels:
    app: security-service-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 10Gi
